version: "0.7.0.{build}"
image: Visual Studio 2019
build:
  project: CommandQuery.sln
  verbosity: minimal
test_script:
  - ps: "dotnet test .\\tests\\CommandQuery.AspNet.WebApi.Tests\\CommandQuery.AspNet.WebApi.Tests.csproj"
  - ps: "dotnet test .\\tests\\CommandQuery.AspNetCore.Tests\\CommandQuery.AspNetCore.Tests.csproj"
  - ps: "dotnet test .\\tests\\CommandQuery.AWSLambda.Tests\\CommandQuery.AWSLambda.Tests.csproj"
  - ps: "dotnet test .\\tests\\CommandQuery.AzureFunctions.Tests\\CommandQuery.AzureFunctions.Tests.csproj"
  - ps: "dotnet test .\\tests\\CommandQuery.Tests\\CommandQuery.Tests.csproj"
